routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@login')->name('auth.login');
Route::post('login', 'AuthController@postLogin')->name('auth.postLogin');
Route::get('register', 'AuthController@register')->name('auth.register');
Route::post('register', 'AuthController@postRegister')->name('auth.postRegister');
Route::get('logout', 'AuthController@logout')->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'MainController@index')->name('main.index');
    Route::get('get-word', 'MainController@getWord')->name('main.word');
    Route::post('check-answer', 'MainController@checkAnswer')->name('main.answer');
});

Route::get('admin', 'AdminController@index')->name('admin.index');

app/History.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{
    protected $fillable = ['user_id', 'word_id', 'point'];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function word()
    {
        return $this->belongsTo('App\Word', 'word_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = ['name', 'email', 'password', 'is_admin', 'point', 'words'];

    protected $hidden = ['password', 'remember_token'];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin'          => 'boolean'
    ];

    public function scopeisAdmin($query)
    {
        return $query->where('is_admin', 1);
    }

    public function scopeisUser($query)
    {
        return $query->where('is_admin', 0);
    }

    public function histories()
    {
        return $this->hasMany('App\History', 'user_id', 'id');
    }

    public function getWordsCountAttribute()
    {
        $array = explode(',', $this->words);

        return count($array) - 1;
    }
}

app/Word.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Word extends Model
{
    protected $fillable = ['word'];

    public function getWordShuffledAttribute()
    {
        return str_shuffle($this->word);
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\History;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index()
    {
        if (auth()->user()->is_admin == false) {
            auth()->logout();

            return redirect(route('auth.login'));
        }

        $histories = History::orderByDesc('created_at')->paginate(25);

        return view('admin')->with('histories', $histories);
    }
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function login()
    {
        return view('login');
    }

    public function register()
    {
        return view('register');
    }

    public function postLogin(Request $request)
    {
        $credential = [
            'email'    => $request->email,
            'password' => $request->password
        ];

        if (auth()->attempt($credential)) {
            if (auth()->user()->isAdmin) {
                return redirect(route('admin.index'));
            }

            return redirect(route('main.index'));
        }

        return back()->withInput()->with([
            'type'    => 'wrong',
            'message' => 'Invalid email or password!'
        ]);
    }

    public function postRegister(Request $request)
    {
        $request->validate([
            'name'     => 'required',
            'email'    => 'required|email|unique:users',
            'password' => 'required|min:6'
        ]);

        $user = User::create([
            'name'     => $request->name,
            'email'    => $request->email,
            'password' => Hash::make($request->password)
        ]);

        if (! $user) {
            return back()->with([
                'type'    => 'wrong',
                'message' => 'Registration error, try again!'
            ]);
        }

        return redirect(route('auth.login'))->with([
            'type'    => 'correct',
            'message' => 'Registration completed!'
        ]);
    }

    public function logout()
    {
        auth()->logout();

        return redirect(route('auth.login'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Word;
use App\History;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {
        return view('main');
    }

    public function getWord()
    {
        $wordIds = ! empty(auth()->user()->words) ? explode(',', auth()->user()->words) : '';
        $word = Word::when(! empty($wordIds), function ($query) use ($wordIds) {
                        return $query->whereNotIn('id', $wordIds);
                    })
                    ->when(config('database.default') == 'mysql', function ($query) {
                        return $query->orderByRaw('RAND()');
                    })
                    ->first();
        $response = [
            'id'       => $word->id,
            'word'     => $word->word_shuffled,
        ];

        return response()->json($response);
    }

    public function checkAnswer(Request $request)
    {
        $wordId = $request->word_id;
        $answer = $request->answer;

        $words = Word::find($wordId);
        $user  = auth()->user();

        // Check answer
        if ($words->word == $answer) {
            $result = ['status' => 'correct', 'point' => 10];

            // Update score & word
            $user->point += $result['point'];
            $user->words = ltrim($user->words.','.$words->id, ',');
        } else {
            $result = ['status' => 'wrong', 'point' => -5];

            // update only score
            $user->point += $result['point'];
        }

        $user->save();

        // Write history
        History::create([
            'user_id' => auth()->user()->id,
            'word_id' => $words->id,
            'point'   => $result['point']
        ]);

        return response()->json($result);
    }
}

resources/views/admin.blade.php
@extends('layout')

@section('body')
    <div class="header">
        <button type="button" class="btn-logout">
            X
        </button>
    </div>

    <div class="table-responsive">
        <table class="table">
            <tr style='text-align: center;'>
                <th>Name</th>
                <th>Points</th>
                <th>Time</th>
            </tr>
            @forelse($histories as $history)
            <tr style='text-align: center;'>
                <td>{{ $history->user->name }}</td>
                <td class="text-center">{{ $history->point > 0 ? '+'.$history->point : $history->point }}</td>
                <td class="text-center">{{ $history->created_at->diffForHumans() }}</td>
            </tr>
            @empty
            <tr style='text-align: center;'>
                <td colspan="3">no data available</td>
            </tr>
            @endforelse
        </table>
        <div class ="pagination" style="position: right;">
            {{ $histories->links() }}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function() {
                $('.btn-logout').click(function() {
                window.location.replace('/logout');
            });
        })
    </script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet'>
    <title>Scramble Words</title>
</head>
<body>
    @yield('body')
</body>
</html>

resources/views/login.blade.php
@extends('layout')

@section('body')
    <div class="head-title">
        <h1><a href="#">Scramble Words</a></h1>
    </div>
    <div class="login-form">
        @if (! empty(session('message')))
            {{ session('message') }}
        @endif
        <form action="{{ route('auth.postLogin') }}" method="POST">
            @csrf
            <input type="text" name="email" placeholder="email" value="{{ old('email') }}" required="required"><br>
            <input type="password" name="password" placeholder="password" required="required"><br>
            <button type="submit" class="btn-login">Lets Play</button>
        </form>
        <a href="{{ route('auth.register') }}" class="register">Register</a>
    </div>
@endsection

resources/views/main.blade.php
@extends('layout')

@section('body')
    <div class="header">
        <button type="button" class="btn-logout">
            X
        </button>
    </div>
    <div class="head-title">
        <h1><a href="#">PLAY NOW</a></h1>
    </div>
    <div class="box-answer-word">
        <span class="notification correct hidden">Benar</span>
        <div class="answer"></div>
    </div>

    <div class="box-button">
    </div>
    <div class="score">
        <div class="box-score">
            <label>SCORE :</label><span id="score">   {{ auth()->user()->point ?? 0 }}</span>
        </div>
    </div> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function() {
            var answer = '';
            var word_id = 0;
            var score = {{ auth()->user()->point ?? 0 }};
            var word_number = {{ auth()->user()->words_count ?? 0 }};

            function erase() {
                answer = '';
                $('.answer').empty();
                $('.box-button button').prop('disabled', false);
                $('.notification').hide();
            }

            function buildButton(word) {
                $('.box-button').empty();

                for(i = 0; i < word.length; i++) {
                    $('.box-button').append('<button type="button"><span>' + word[i] + '</span></button>');

                    if (i == 2 || i == 5) {
                        $('.box-button').append('<br>');
                    }
                }

                $('.box-button').append('<button type="button" class="btn-erase"><span><<</span></button>');
            }

            function getWord() {
                $.ajax({
                    method: 'GET',
                    url: '{{ route('main.word') }}'
                }).done(function(data) {
                    erase();
                    buildButton(data.word);

                    word_id = data.id;

                    $('.box-button button').bind('click', function() {
                        $(this).prop('disabled', true);
                        $('.answer').append($(this).html());

                        answer += $(this).children().html();

                        if (answer.length == data.word.length) {
                            $('.btn-erase').prop('disabled', true);

                            checkAnswer(word_id, answer);
                        }
                    });

                    $('.btn-erase').bind('click', function() {
                        erase();
                    });
                });
            }

            function checkAnswer(id, data) {
                $.ajax({
                    method: 'POST',
                    url: '{{ route('main.answer') }}',
                    data: {'_token'  : $('meta[name="csrf-token"]').attr('content'),'word_id': id, 'answer': data},
                }).done(function(data) {
                    if (data.status == 'correct') {
                        score += data.point;
                        $("#score").html(score);
                        word_number++;
                        $("#word_number").html(word_number);

                        $('.notification').removeClass('wrong').addClass('correct').html(data.status + ' +' + data.point).fadeIn(1000).fadeOut(3000);
                        setTimeout(function() {
                            getWord();
                            $('.btn-erase').prop('disabled', false);
                        }, 3000);
                    } else if (data.status == 'wrong') {
                        score += data.point;
                        $("#score").html(score);

                        $('.notification').removeClass('correct').addClass('wrong').html(data.status + ' ' + data.point).fadeIn(1000).fadeOut(3000);
                    $('.btn-erase').prop('disabled', false);
                    }
                });
            }

            $('.btn-logout').click(function() {
                window.location.replace('/logout');
            });

            getWord();
        });
    </script>
@endsection

resources/views/register.blade.php
@extends('layout')

@section('body')
    <div class="head-title">
        <h1><a href="#">Scramble Words</a></h1>
    </div>
    <div class="login-form">
        @if (! empty(session('message')))
            {{ session('message') }}
        @endif
        @if (! empty($errors))
            {{ $errors->first() }}
        @endif
        <form action="{{ route('auth.postRegister') }}" method="POST">
            @csrf
            <input type="text" name="name" placeholder="name" value="{{ old('name') }}" required="required"><br>
            <input type="text" name="email" placeholder="email" value="{{ old('email') }}" required="required"><br>
            <input type="password" name="password" placeholder="password" required="required"><br>
            <button type="submit" class="btn-login">Register</button>
        </form>
        <a href="{{ route('auth.login') }}" class="register">Already have account</a>
    </div>
@endsection